#!/usr/bin/env bash

# Script to create an RSA SSH key pair named "school" with 4096 bits and passphrase "betty"

# Variables
KEY_NAME="school"
PASSPHRASE="betty"
KEY_BITS=4096

# Generate the SSH key
ssh-keygen -t rsa -b $KEY_BITS -f $KEY_NAME -N $PASSPHRASE
