#!/usr/bin/env bash
# Installs and configures HAProxy as a load balancer

apt-get update -y
apt-get install haproxy -y

# Backup original config
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Configure HAProxy
cat > /etc/haproxy/haproxy.cfg << 'HAPROXYCONFIG'
global
	log /dev/log	local0
	log /dev/log	local1 notice
	chroot /var/lib/haproxy
	stats socket /run/haproxy/admin.sock mode 660 level admin
	stats timeout 30s
	user haproxy
	group haproxy
	daemon

defaults
	log	global
	mode	http
	option	httplog
	option	dontlognull
	timeout connect 5000
	timeout client  50000
	timeout server  50000

frontend http_front
	bind *:80
	default_backend http_back

backend http_back
	balance roundrobin
	server 6921-web-01 100.26.206.13:80 check
	server 6921-web-02 54.211.4.59:80 check
HAPROXYCONFIG

# Enable HAProxy init script
echo "ENABLED=1" > /etc/default/haproxy

# Restart HAProxy
service haproxy restart
