#!/usr/bin/env bash
# Transfers a file from client to server using scp

if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else 
	file_path="$1"
	IP_address="$2"
	username="$3"
	private_key="$4"
	scp -i "$private_key" "$file_path" "$3@$2:~/"
fi
