#!/usr/bin/env bash
# Configures Nginx server to listen on port 80 and return "Holberton School"

apt-get update -y
apt-get install nginx -y
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
service nginx start
