#!/usr/bin/env bash
# Configures Nginx server with a 301 redirect for /redirect_me

apt-get update -y
apt-get install nginx -y

# Create the index page
echo "Holberton School for the win!" > /var/www/html/index.html

# Configure the redirect in the Nginx default configuration
sed -i '/server_name _;/a \\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-available/default

# Start nginx service
service nginx start
